---
title: "Clima"
output:
  pdf_document: default
  html_document: default
---

# Packages
```{r}
library(latticeExtra)
```

# Set directory
```{r}
setwd("C:\\Users\\")
```

# Read data
## Coluna day é continuo entre os meses do mesmo ano.
```{r}
dados <- read.table("climas.txt", header = T) # Ler tabela
```

# First lines
```{r}
head(dados)
```
       year month day      max      min chuva
2015/2016   Oct   1 24.50000 22.58750   2.6
2015/2016   Oct   2 24.10417 22.76250   0.0
2015/2016   Oct   3 25.31250 23.41250   0.0
2015/2016   Oct   4 24.96250 23.25000   0.0
2015/2016   Oct   5 21.91250 20.91250   0.0
2015/2016   Oct   6 20.29583 18.99583   0.0

# Last lines
```{r}
tail(dados)
```
    year month day      max      min chuva
2016/2017   Apr 207 21.13750 19.91667   0.0
2016/2017   Apr 208 20.64167 19.72500   0.0
2016/2017   Apr 209 23.03750 21.56667   4.2
2016/2017   Apr 210 19.30833 18.92083   6.2
2016/2017   Apr 211 17.80833 17.37917   0.0
2016/2017   Apr 212 18.09583 17.38333   0.2

# Prepare Data
```{r}
max <- dados$max
min <- dados$min
prec <- dados$chuva
y_range <- range(0, max, min) # determinar eixo Y
x_range <- range(0:212) # determinar eixo X
```

# Plot type
```{r}
png("arr.png", res=600, width=40, height=20, units="cm")
```

# Plot temperature graph
```{r}
g1 <- xyplot(min + max ~ day| year , data = dados, type = "l", xlim = x_range, ylim = y_range, 
           lty = 1, lwd = 0.6, ylab = list(label = "Temperature (C°)", cex = 1.3), ylab.right = list(label = "Rainfall (mm)", cex = 1.3),
           xlab = list(label = "Month", cex = 1.3), layout = c(1,2), index.cond = list(c(2,1)),
           scales = list(x = list(at = 30*0.5:212, label = c("Oct","Nov","Dec","Jan","Feb","Mar","Apr"), cex = 1.3)),
           strip = strip.custom(bg = "gray90", strip.names = TRUE, var.name = "Growing Season"))

```

# Plot arrows
```{r}
g2 <- g1 + layer(panel.arrows(112,15,112,20, col = "red", code = 1, lwd = 2),
                panel.arrows(172,15,172,20, col = "blue", code = 1, lwd = 2),
                panel.arrows(40,15,40,20, col = "black", code = 1, lwd = 2))
```

# Plot rainfall graph
```{r}
g3<-xyplot(prec ~ day| year , data = dados, type ="h",col="black",lwd=2)
```

# Join graphs
```{r}
graph <- doubleYScale(g2, g3, style1 = 0, style2 = 0,
                    text = c("Minimun Temperature", "Maximun Temperature", "Rainfall"), columns = 3)
```

# Graph colors
```{r}
update(trellis.last.object(),
       par.settings = simpleTheme(col = c("blue", "red", "black")))
```

# Save graph
```{r}
dev.off()
```

